### ISSUE TITLE
Implementation of configuration creation through dependencies.

### ISSUE THREAD

**Issue by magic-element** [sunshard-prism/prism-nomad#117]
It is necessary to implement the functionality of creating configurations from the list of dependencies specified in the pack.yaml file.
```
dependencies:
  - name: "dependency-name"
    pack_version: "0.0.1"
    path: "/path/to/pack"
    files:
     - "dependency_overrides.yaml"
```

Implementing dependencies involves creating additional jobs that will be deployed before deploying the jobs for which they are described.
